services:
  course-services:
    build: .
    env_file: .env
    ports:
      - "${COURSE_SERVICE_APP_PORT}:80"
    depends_on:
      - course-service-db
    networks:
      - course-service-net
      - backend-net

  course-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${COURSE_SERVICE_DATABASE_USER}
      POSTGRES_PASSWORD: ${COURSE_SERVICE_DATABASE_PASSWORD}
      POSTGRES_DB: ${COURSE_SERVICE_DATABASE_DB}
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "${COURSE_SERVICE_DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./course-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - course-service-net

volumes:
  postgres-data:

networks:
  course-service-net:
  backend-net:
    external: true
